services:
  dikidi_backend:
    image: dikidi-b
    container_name: dikidi_backend
    labels:
      - "io.portainer.accesscontrol.teams=bogoko"
    restart: always
    env_file:
      - .env
    # ports:
    #   - 5000:5000
    networks:
      - dikidi
  
networks:
  dikidi:
    name: dikidi
    external: true
