services:
  dikidi_backend:
    image: dikidi-b
    container_name: dikidi_backend
    restart: always
    env_file:
      - deploy.env
    ports:
      - 5000:5000
    networks:
      - dikidi
  
networks:
  dikidi:
    name: dikidi