services:
  dikidi_backend:
    image: dikidi-b
    container_name: dikidi_backend
    restart: always
    # ports:
    #   - 3000:3000
    networks:
      - dikidi
  
networks:
  dikidi:
    name: dikidi